spring:
  cloud:
    nacos:
      discovery:
        server-addr:127.0.0.1:8848
    gateway:
      routes:
        - id: xzoj-backend-user-service
          uri: lb://xzoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: xzoj-backend-question-service
          uri: lb://xzoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: xzoj-backend-judge-service
          uri: lb://xzoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: xzoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
